#spring:
#  datasource:
#    url: jdbc:sqlserver://yogesh-server.database.windows.net:1433;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    username: yogesh
#    password: Yadav@2003
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      dialect : org.hibernate.dialect.SQLServer2012Dialect
#
#server:
#  port: 8080